#!/usr/bin/env bash
#script that doubles the number of webservers and adds new configs

#install nginx
apt-get update ; apt-get -y install nginx

string="http {\n\tadd_header X-Served-By \"$HOSTTNAME\";"
sudo sed -i "s/http {/$stringg/" /etc/nginx/nginx.conf
#restart nginx
sudo service nginx restart
