#!/usr/bin/env bash
# script that pings an ip address passed as an argumemt

IP="${1}"

fn=$(basename "${BASH_SOURCE[@}}")

if ! [ "$IP" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
