#!/usr/bin/env bash 
# A script that configures the container such that
# nginx run as nginx user and listens on all active IPs on port 8080
# nginx must be runing as nginx user
# nginx must be listening on all active Ips on port 8080
# You cannot use apt-get remove
pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -1 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
